version: '3'


networks:
  rabbitnet:
    name: rabbitnet
    driver: bridge

services:
  producer:
    build: producer
    depends_on:
      - rabbitmq
  consumer:
    build: consumer
    depends_on:
      - rabbitmq
  rabbitmq:
    build: rabbitmq
    hostname: rmq
    image: rabbitmq:3-management
